/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	uint32_t *APB2ENR = (uint32_t *)(0x40021000 + 0x18);//GPIOB is here
	uint32_t *APB1ENR = (uint32_t *)(0x40021000 + 0x1C);//I2C1 is here
	uint32_t *CRL = (uint32_t *)(0x40010800 + 0x00);//PB7 and PB6
	uint32_t *CR1 = (uint32_t *)(0x40005000 + 0x00);//Enable i2C peripheral
	uint32_t *CR2 = (uint32_t *)(0x40005000 + 0x04);//Enable peripheral clock frequency
	uint32_t *CCR = (uint32_t *)(0x40005000 + 0x1C);//Enables I2C bus frequency
	uint32_t *DR = (uint32_t *)(0x40005000 + 0x10);//Enables data register
	uint32_t *SR1 = (uint32_t *)(0x40005000 + 0x14);//To check ACK
	uint32_t *SR2 = (uint32_t *)(0x40005000 + 0x18);//To read and clear ACK
	uint32_t *Trise = (uint32_t *)(0x40005000 + 0x20);//To configure max rise time
	*APB2ENR |= (1<<3) | (1<<4);
	*APB1ENR |= (1<<21);
	*CRL &= ~((0xf<<24)|(0xf<<28));
	*CRL |= (0xd<<24)|(0xd<<28);
	*CR2 &= ~(0x3f<<0);
	*CR2 |= (1<<3);
	*CCR &= ~(0xfff << 0);
	*CCR |= (40 << 0);// 100kHz I2C speed with 8MHz APB1 clock required
	*Trise &= ~(0x3f << 0 );
	*Trise |=(0x9<<0);//For standard mode 100kHz with 8Mhz
	*CR1 |=(1<<0);//Enable the peripheral bit (PE)
	*CR1 |= (1<<8);//generates START condition
	while(!(*SR1 & (1<<0)));//Until START condition is sent SR1's 0bit will stay zero and loop will keep running
	*DR = 0x78;//Address for the oled display is 0x3c and R/W needs 0(for writing) so 0x3c<<1 hence R/W at bit 0 is 0
	while(!(*SR1 & (1<<1)));//Until it is confirmed that address is acknowledged loop will run
	(void)(*SR2);//Read SR2 to clear ADDR flag
	*DR = 0x00;//Dummy byte to prove that I2C is working
	while(!(*SR1 & (1<<7)));//Confirms Data register is empty now
	*CR1 |=(1<<9);//Generate STOPs. STOPs the whole peripheral
}
